-- New standards introduced in 2025 data
INSERT INTO standards (standard_number,title,credits,assessment_type,standards_type,is_ue,subject,search_keywords)
VALUES
(575,'Use and care for farm horses',10,'Internal','Unit',FALSE,'Farming Skills','{"primary": ["575"], "groups": []}'::jsonb),
(2201,'Template and construct an assembly jig for wooden furniture',6,'Internal','Unit',FALSE,'Furniture and Cabinet Making','{"primary": ["2201"], "groups": []}'::jsonb),
(2626,'Hand press a garment',3,'Internal','Unit',FALSE,'Apparel Cutting and Sewing','{"primary": ["2626"], "groups": []}'::jsonb),
(2884,'Cut hair into foundation forms with scissors and clippers',20,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["2884"], "groups": []}'::jsonb),
(6924,'Trim and cut tree stems on a landing and assess quality of own processing work',10,'Internal','Unit',FALSE,'Forest Landing Operations','{"primary": ["6924"], "groups": []}'::jsonb),
(9913,'Demonstrate knowledge of the New Zealand marine and composite industry',5,'Internal','Unit',FALSE,'Boatbuilding','{"primary": ["9913"], "groups": []}'::jsonb),
(13008,'Demonstrate knowledge of formwork for footings and foundation walls up to 1.2 metres tall',3,'Internal','Unit',FALSE,'Carpentry','{"primary": ["13008"], "groups": []}'::jsonb),
(13009,'Demonstrate knowledge of using reinforcing steel for construction',1,'Internal','Unit',FALSE,'Carpentry','{"primary": ["13009"], "groups": []}'::jsonb),
(13059,'Install mechanical fixings and building hardware under supervision',2,'Internal','Unit',FALSE,'Carpentry','{"primary": ["13059"], "groups": []}'::jsonb),
(14426,'Prepare, take orders, and serve bottled wines in a licensed commercial environment',4,'Internal','Unit',FALSE,'Food and Beverage Service','{"primary": ["14426"], "groups": []}'::jsonb),
(17204,'Describe sustainable land management in the New Zealand environment, society and economy',10,'Internal','Unit',FALSE,'Agricultural Resource Maintenance','{"primary": ["17204"], "groups": []}'::jsonb),
(18692,'Raranga t?peka',4,'Internal','Unit',FALSE,'Raranga','{"primary": ["18692"], "groups": []}'::jsonb),
(19070,'Harvest cash crops under supervision',5,'Internal','Unit',FALSE,'Arable Farming','{"primary": ["19070"], "groups": []}'::jsonb),
(20057,'Demonstrate knowledge of business and quality principles in the print industry',10,'Internal','Unit',FALSE,'Printing Production','{"primary": ["20057"], "groups": []}'::jsonb),
(20644,'Demonstrate knowledge of the Animal Welfare Act in a primary industry operation',5,'Internal','Unit',FALSE,'Primary Sector Core Skills','{"primary": ["20644"], "groups": []}'::jsonb),
(20751,'Operate a cross cut saw centre',5,'Internal','Unit',FALSE,'Sawmilling','{"primary": ["20751"], "groups": []}'::jsonb),
(20869,'Demonstrate knowledge of notifiable works and work permits typical of infrastructure worksites',3,'Internal','Unit',FALSE,'Generic Infrastructure Works','{"primary": ["20869"], "groups": []}'::jsonb),
(21047,'Describe, prepare, and apply liquid fertilisers used in organic horticulture',5,'Internal','Unit',FALSE,'Production Horticulture','{"primary": ["21047"], "groups": []}'::jsonb),
(21332,'Demonstrate knowledge of establishing improvements in a manufacturing environment',4,'Internal','Unit',FALSE,'Manufacturing Processes','{"primary": ["21332"], "groups": []}'::jsonb),
(23578,'Demonstrate and apply knowledge to controlled waste in loads entering a solid waste facility',6,'Internal',NULL,FALSE,'Solid Waste Disposal','{"primary": ["23578"], "groups": []}'::jsonb),
(23760,'Work in a team on a tourism workplace task or project',3,'Internal','Unit',FALSE,'Visitor Services','{"primary": ["23760"], "groups": []}'::jsonb),
(24094,'Demonstrate knowledge of windscreen wiper and headlamp cleaning systems',1,'Internal','Unit',FALSE,'Automotive Electrical and Electronics','{"primary": ["24094"], "groups": []}'::jsonb),
(24401,'Install wall and ceiling insulation under supervision',1,'Internal','Unit',FALSE,'Carpentry','{"primary": ["24401"], "groups": []}'::jsonb),
(24411,'Machine brake disc rotors and brake drums',2,'Internal','Unit',FALSE,'Vehicle Braking Systems','{"primary": ["24411"], "groups": []}'::jsonb),
(25956,'Open and close aircraft passenger cabin doors externally',3,'Internal','Unit',FALSE,'Ramp Operations','{"primary": ["25956"], "groups": []}'::jsonb),
(26323,'Generate basic imposition schemes and impose pages for printing',5,'Internal','Unit',FALSE,'Printing Production','{"primary": ["26323"], "groups": []}'::jsonb),
(26784,'Maintain daily records for an infrastructure worksite',5,'Internal','Unit',FALSE,'Generic Infrastructure Works','{"primary": ["26784"], "groups": []}'::jsonb),
(26972,'Describe interventions and models used when working with a person accessing mental health and addiction services',4,'Internal','Unit',FALSE,'Mental Health and Addiction Support','{"primary": ["26972"], "groups": []}'::jsonb),
(27123,'Identify whakapapa and explain intermarriage',4,'Internal','Unit',FALSE,'Tikanga Concepts','{"primary": ["27123"], "groups": []}'::jsonb),
(27168,'Select and recommend nail products for use at home',3,'Internal','Unit',FALSE,'Salon Skills','{"primary": ["27168"], "groups": []}'::jsonb),
(27217,'Describe key features, principles and benefits of integrated pest management in the primary sector',5,'Internal','Unit',FALSE,'Plant Pest, Weed, and Disease Control','{"primary": ["27217"], "groups": []}'::jsonb),
(27349,'Demonstrate knowledge of theory and legislation for registration of electrical service technicians',3,'Internal','Unit',FALSE,'Electrical Standards and Statutes','{"primary": ["27349"], "groups": []}'::jsonb),
(27712,'Instruct a Free Weights class',7,'Internal','Unit',FALSE,'Fitness Assessment and Exercise Instruction','{"primary": ["27712"], "groups": []}'::jsonb),
(27716,'Instruct a Mind and Body class',7,'Internal','Unit',FALSE,'Fitness Assessment and Exercise Instruction','{"primary": ["27716"], "groups": []}'::jsonb),
(27731,'Demonstrate knowledge of working within an aeronautical engineering workplace',4,'Internal','Unit',FALSE,'Aeronautical Engineering - Core','{"primary": ["27731"], "groups": []}'::jsonb),
(27910,'Demonstrate and apply knowledge of stakeholder engagement in an electrotechnology or telecommunications environment',5,'Internal','Unit',FALSE,'Electrotechnology','{"primary": ["27910"], "groups": []}'::jsonb),
(27911,'Demonstrate knowledge of workplace safety in an electrotechnology or telecommunications environment',10,'Internal','Unit',FALSE,'Electrotechnology','{"primary": ["27911"], "groups": []}'::jsonb),
(27912,'Demonstrate knowledge of electrical principles in an electrotechnology or telecommunications environment',15,'Internal','Unit',FALSE,'Electrotechnology','{"primary": ["27912"], "groups": []}'::jsonb),
(27948,'Package and transport prepared catering items for a catering services operation',5,'Internal','Unit',FALSE,'Catering Services','{"primary": ["27948"], "groups": []}'::jsonb),
(28031,'Demonstrate knowledge of human performance in aeronautical engineering',5,'Internal','Unit',FALSE,'Aeronautical Engineering - Core','{"primary": ["28031"], "groups": []}'::jsonb),
(28547,'Support a person with diabetes in a health or wellbeing setting',3,'Internal','Unit',FALSE,'Core Health','{"primary": ["28547"], "groups": []}'::jsonb),
(29327,'Demonstrate knowledge of small business practices in the beauty services industry',5,'Internal','Unit',FALSE,'Salon Skills','{"primary": ["29327"], "groups": []}'::jsonb),
(29559,'Identify and explain M?ori models of hauora and explain how these models can be implemented in a health organisation',4,'Internal','Unit',FALSE,'Hauora','{"primary": ["29559"], "groups": []}'::jsonb),
(29764,'Deliver an alcoholic beverage tasting experience for a tourism workplace',6,'Internal','Unit',FALSE,'Visitor Services','{"primary": ["29764"], "groups": []}'::jsonb),
(29836,'Pack and dispatch pre-graded nursery plant products and complete documentation',5,'Internal','Unit',FALSE,'Nursery Production','{"primary": ["29836"], "groups": []}'::jsonb),
(30613,'Install trade waste interceptor traps',2,'Internal','Unit',FALSE,'Drainlaying','{"primary": ["30613"], "groups": []}'::jsonb),
(30617,'Explain wh?nau ora and whanaungatanga',6,'Internal','Unit',FALSE,'Wh?nau Ora','{"primary": ["30617"], "groups": []}'::jsonb),
(30641,'Demonstrate knowledge of electromechanical engineering principles for technicians',10,'Internal','Unit',FALSE,'Electrotechnology','{"primary": ["30641"], "groups": []}'::jsonb),
(30642,'Demonstrate knowledge of specialist equipment used in electronic repairs',5,'Internal','Unit',FALSE,'Core Electronics','{"primary": ["30642"], "groups": []}'::jsonb),
(30643,'Demonstrate knowledge of the installation of electrotechnology systems on customer premises',10,'Internal','Unit',FALSE,'Electrotechnology','{"primary": ["30643"], "groups": []}'::jsonb),
(30644,'Demonstrate basic knowledge of diagnostics and fault finding for service and installation technicians',5,'Internal','Unit',FALSE,'Electrotechnology','{"primary": ["30644"], "groups": []}'::jsonb),
(30651,'Explain regulatory requirements for installing and servicing extra-low and low voltage customer premises systems',5,'Internal','Unit',FALSE,'Electrotechnology','{"primary": ["30651"], "groups": []}'::jsonb),
(31245,'Plan for and lift, move, and place loads using mobile plant',10,'Internal','Unit',FALSE,'Generic Infrastructure Works','{"primary": ["31245"], "groups": []}'::jsonb),
(31284,'Demonstrate understanding and skills to construct manu aute',3,'Internal','Unit',FALSE,'Taonga','{"primary": ["31284"], "groups": []}'::jsonb),
(31457,'Demonstrate knowledge of working around services for infrastructure works',5,'Internal','Unit',FALSE,'Generic Infrastructure Works','{"primary": ["31457"], "groups": []}'::jsonb),
(31536,'Contribute to the review of outdoor activity and reflect on own assistant leadership',3,'Internal','Unit',FALSE,'Outdoor Management','{"primary": ["31536"], "groups": []}'::jsonb),
(32005,'Organise small business meetings',3,'Internal','Unit',FALSE,'Business Administration Services','{"primary": ["32005"], "groups": []}'::jsonb),
(32387,'Demonstrate knowledge of and comply with documentation requirements for pest operations, and communicate with personnel',3,'Internal','Unit',FALSE,'Pest Control','{"primary": ["32387"], "groups": []}'::jsonb),
(32446,'Demonstrate knowledge of installing interior joinery',2,'Internal','Unit',FALSE,'Carpentry','{"primary": ["32446"], "groups": []}'::jsonb),
(32458,'Demonstrate knowledge of commercial falsework and formwork',3,'Internal','Unit',FALSE,'Carpentry','{"primary": ["32458"], "groups": []}'::jsonb),
(32461,'Demonstrate knowledge of wall framing and prefabricated beams',5,'Internal','Unit',FALSE,'Carpentry','{"primary": ["32461"], "groups": []}'::jsonb),
(32492,'Demonstrate knowledge of installing exterior joinery',2,'Internal','Unit',FALSE,'Carpentry','{"primary": ["32492"], "groups": []}'::jsonb),
(32614,'Demonstrate knowledge of electrical faults, circuit protection, de-commissioning, and commissioning',6,'Internal','Unit',FALSE,'Core Electrical','{"primary": ["32614"], "groups": []}'::jsonb),
(32767,'Demonstrate knowledge of lifting and moving loads for infrastructure works',5,'Internal','Unit',FALSE,'Generic Infrastructure Works','{"primary": ["32767"], "groups": []}'::jsonb),
(32802,'Describe rodent feeding, health, housing, and routine health procedures',3,'Internal','Unit',FALSE,'Animal Care','{"primary": ["32802"], "groups": []}'::jsonb),
(32994,'Communicate and support the use of languages to develop and maintain relationships in an early childhood setting',4,'Internal','Unit',FALSE,'Early Childhood: Family, Wh?nau, Community, and Society','{"primary": ["32994"], "groups": []}'::jsonb),
(32995,'Demonstrate knowledge of Te Tiriti o Waitangi, legislation, services and support relevant to an early childhood setting',4,'Internal','Unit',FALSE,'Early Childhood: Family, Wh?nau, Community, and Society','{"primary": ["32995"], "groups": []}'::jsonb),
(33199,'Demonstrate knowledge of and apply shampoo and treatments to the hair and scalp',6,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33199"], "groups": []}'::jsonb),
(33202,'Blow dry hair',8,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33202"], "groups": []}'::jsonb),
(33203,'Set hair to create volume, direction and movement',12,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33203"], "groups": []}'::jsonb),
(33205,'Demonstrate knowledge of common scalp conditions and skin irregularities',5,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33205"], "groups": []}'::jsonb),
(33210,'Demonstrate knowledge of hair cutting foundations',8,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33210"], "groups": []}'::jsonb),
(33212,'Describe and analyse the economic, socio-cultural, and environmental impacts of tourism',5,'Internal','Unit',FALSE,'Visitor Services','{"primary": ["33212"], "groups": []}'::jsonb),
(33220,'Apply oxidative colour to and remove it from the hair and scalp',5,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33220"], "groups": []}'::jsonb),
(33223,'Demonstrate knowledge of the effect of chemical processes on hair texture',7,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33223"], "groups": []}'::jsonb),
(33225,'Assist with chemical reformation services',3,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33225"], "groups": []}'::jsonb),
(33226,'Perform elementary hair cutting services with scissors and clippers',10,'Internal','Unit',FALSE,'Hairdressing','{"primary": ["33226"], "groups": []}'::jsonb),
(33232,'Apply knowledge of health and safety requirements in the salon environment',2,'Internal','Unit',FALSE,'Salon Skills','{"primary": ["33232"], "groups": []}'::jsonb),
(33353,'Give a spoken presentation in Gagana Tokelau to explore and justify information, ideas and perspectives',3,'Internal','Unit',FALSE,'Gagana Tokelau','{"primary": ["33353"], "groups": []}'::jsonb),
(40045,'Apply customer service techniques to provide quality customer service interactions',10,'Internal',NULL,FALSE,'Service Delivery','{"primary": ["40045"], "groups": []}'::jsonb),
(40735,'Operate a forklift safely',4,'Internal',NULL,FALSE,'Powered Industrial Lift Trucks','{"primary": ["40735"], "groups": []}'::jsonb)
ON CONFLICT (standard_number) DO NOTHING;
